
@baseUrl = http://localhost:8000/api/vendas/produtos-vendidos
@token = 43|f8iBpG0cNvImhNcAFs5NadEb8JsBAWFJkXdDn6ul38e41e66

### Get User (Authenticated)
GET {{baseUrl}}/
Authorization: Bearer {{token}}
