### Create a new account
POST http://localhost:8000/api/conta
Content-Type: application/json
Authorization: Bearer 5|Z2HXf7GYRzoSSgrFHe1rhEF0YiGQKRkI0tTrBpSuadba4553

{
    "titulo": "Bandeira para um clube de futebol",
    "descricao": "Cliente chato",
    "valor": 6500.50,
    "data_vencimento": "2023-12-31",
    "status": "recebido",
    "tipo": "a receber",
}

