@baseUrl = http://localhost:8000/api/conta/5

### Update Account
PUT {{baseUrl}}
Content-Type: application/json
Authorization: Bearer 5|Z2HXf7GYRzoSSgrFHe1rhEF0YiGQKRkI0tTrBpSuadba4553

{
  "valor": 2000
}

