### Testar a rota de clientes consolidados
GET https://api-homolog.spacearena.net/api/clientes-consolidados
# GET http://localhost:8000/api/clientes-consolidados
Accept: application/json
Authorization: Bearer 38|1k9JUhoi3CYqbmBkcnyOAwsPVnopPt0k6p5OYLry3c1d3704




