### Testar a rota de clientes consolidados
#GET https://api-homolog.spacearena.net/api/clientes-consolidados
GET http://localhost:8000/api/clientes-consolidados
Accept: application/json
Authorization: Bearer 3|Xnadurg0vbmI8f7qoEA9us2tq3oIBlujmwqFisxie10613c6






