### upsert-pacote
PUT http://localhost:8000/api/produto/pacote/uniforme/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer 127|SwAK1za7lMED7SACGQ6LhScICB72f7OFSZenABi209d587de

{
    "nome": "Start",
    "tipo_de_tecido": "Dryfit Liso",
    "permite_gola_customizada": true,
    "tipo_gola": ["V"],
    "permite_nome_de_jogador": true,
    "permite_escudo": true,
    "tipo_de_escudo_na_camisa": ["Escudo no peito"],
    "tipo_de_escudo_no_calcao": ["Escudo no calção"],
    "patrocinio_ilimitado": true,
    "tamanhos_permitidos": ["P", "M", "G", "GG"],
    "numero_fator_protecao_uv_camisa": 50,
    "numero_fator_protecao_uv_calcao": 30,
    "tipo_de_tecido_meiao": "Helanca Profissional",
    "punho_personalizado": true,
    "etiqueta_de_produto_autentico": true,
    "logo_totem_em_patch_3d": true,
    "selo_de_produto_oficial": true,
    "selo_de_protecao_uv": true
}
