### upsert-pacote
# PUT https://api-homolog.spacearena.net/api/produto/pacote/uniforme/ HTTP/1.1
# PUT https://api.spacearena.net/api/produto/pacote/uniforme/ HTTP/1.1
PUT http://localhost:8000/api/produto/pacote/uniforme/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 122|F67qRzAO1OLMtHOgxZfrBCnUIvDXsV1UFGz51bB3d2ae4e58

{
    "nome": "Profissional",
    "tipo_de_tecido_camisa": "Dryfit Camb Pro",
    "tipo_de_escudo_na_camisa": ["Patch 3D"],
    "permite_gola_customizada": false,
    "tipo_gola": ["Polo", "Careca", "V", "Bayard"],
    "patrocinio_ilimitado": true,
    "punho_personalizado": true,
    "etiqueta_de_produto_autentico": true,
    "logo_totem_em_patch_3d": true,
    "selo_de_produto_oficial": true,
    "tamanhos_permitidos": ["PP", "P", "M", "G", "GG", "XG", "XXG", "XXXG"],
    "permite_nome_de_jogador": true,
    "selo_de_protecao_uv": true,
    "numero_fator_protecao_uv_camisa": 50,
    "tipo_de_tecido_calcao": "Dryfit Camb Pro",
    "permite_escudo": false,
    "tipo_de_escudo_no_calcao": ["Patch 3D"],
    "numero_fator_protecao_uv_calcao": 50,
    "tipo_de_tecido_meiao": "Helanca Profissional Premium"
}