@token = 5|dgk5QKcJ02WGg8pVWi3Ib5o5DBGreEwDBWZRnw3P53ea9300


### Get All Users
GET http://localhost:8000/api/super-admin/get-all-modules
Authorization: Bearer {{token}}
Content-Type: application/json
