@token = 27|Y5uk9rifU0t6oBKUu3sH0oT4zWM8PTnvOFHwkaM9d32ae1b9


### Get All Users
GET http://localhost:8000/api/super-admin/get-all-users
Authorization: Bearer {{token}}
Content-Type: application/json
