PUT http://localhost:8000/api/super-admin/config
Content-Type: application/json
Authorization: Bearer 5|dgk5QKcJ02WGg8pVWi3Ib5o5DBGreEwDBWZRnw3P53ea9300

{
  "user_id": 1,
  "custo_tecido": 20.5,
  "custo_tinta": 30.3,
  "custo_papel": 7.2,
  "custo_imposto": 5.0
}
