PUT http://localhost:8000/api/orcamentos/345/status
Content-Type: application/json
Authorization: Bearer 120|xgXEkOzQ2MRQpc5eapkISZF1ie4wrEQVgu0YA7AZ20468338

{
  "status_type": "status_pagamento",
  "status_value": "pago",
  "comentarios": "Pagamento confirmado."
}