### Create a new account

POST http://localhost:8000/api/custo-bandeira
Content-Type: application/json
Authorization: Bearer 13|irnWyBmt5tTFRjywlqTYah741OFoHlM78pD9XYVfde2f8d33

{
  "altura": 100,
  "largura": 50,
  "custo_tecido": 20.5,
  "custo_tinta": 30.3,
  "custo_papel": 7.2,
  "custo_imposto": 5.0,
  "custo_final": 100.0
}
