### Create a new account

POST http://localhost:8000/api/custo-bandeira
Content-Type: application/json
Authorization: Bearer 11|Z3d6GZ4FS0bzBRgCDaoRcftF89f7RiU3l9nce9Wsd6e8dc95

{
    "altura": 2.5,
    "largura": 1.5,
    "custo_tecido": 20.0,
    "custo_tinta": 15.0,
    "custo_papel": 5.0,
    "custo_imposto": 8.0,
    "custo_final": 48.0
}
