<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrmClientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clientes = [
            [
                'id' => 24010170001,
                'nome' => 'Rafael Silva',
                'telefone' => '+55 11 98765 4321',
                'email' => '11987654321@octachat.com',
                'origem' => NULL,
                'url_octa' => 'f330f4b1-a7ed-4de9-bb9f-16d33687bdfd',
                'created_at' => '2024-01-01 10:30:00',
                'updated_at' => '2024-01-01 10:30:00',
                'primeira_mensagem_cliente' => 'Bom dia, gostaria de um orçamento',
                'responsavel_contato' => 'Arte Arena Site',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170002,
                'nome' => 'Maria Santos - 14522',
                'telefone' => '+55 21 99876 5432',
                'email' => '21998765432@octachat.com',
                'origem' => NULL,
                'url_octa' => '81af1a58-a5e4-4237-8da0-71f75919157c',
                'created_at' => '2024-01-01 11:15:00',
                'updated_at' => '2024-01-01 11:15:00',
                'primeira_mensagem_cliente' => 'Olá, preciso de uma bandeira personalizada',
                'responsavel_contato' => 'Giovana',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Bandeira Personalizada',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170003,
                'nome' => 'Pedro Oliveira',
                'telefone' => '+55 31 98765 4321',
                'email' => '31987654321@octachat.com',
                'origem' => NULL,
                'url_octa' => '197c23f2-af0f-4f17-9ac9-248b647253cf',
                'created_at' => '2024-01-01 13:45:00',
                'updated_at' => '2024-01-01 13:45:00',
                'primeira_mensagem_cliente' => 'Boa tarde, quero fazer um orçamento',
                'responsavel_contato' => 'Arte Arena Site',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170004,
                'nome' => 'Ana Costa - 14525',
                'telefone' => '+55 41 99876 5432',
                'email' => '41998765432@octachat.com',
                'origem' => NULL,
                'url_octa' => '6f1534b8-1557-46ef-a837-767efab29fe9',
                'created_at' => '2024-01-01 14:20:00',
                'updated_at' => '2024-01-01 14:20:00',
                'primeira_mensagem_cliente' => 'Preciso de um banner urgente',
                'responsavel_contato' => 'Giovana',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => '2024-01-05 10:00:00',
                'status_conversa' => NULL,
                'mensagem_template_id' => '51',
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170005,
                'nome' => 'Lucas Ferreira',
                'telefone' => '+55 51 98765 4321',
                'email' => '51987654321@octachat.com',
                'origem' => NULL,
                'url_octa' => '27b78c26-51db-4642-80a7-a8da1754bd80',
                'created_at' => '2024-01-01 15:10:00',
                'updated_at' => '2024-01-01 15:10:00',
                'primeira_mensagem_cliente' => 'Olá, quanto custa uma bandeira?',
                'responsavel_contato' => 'Arte Arena Site',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Bandeira Personalizada',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170006,
                'nome' => 'Juliana Lima - 14530',
                'telefone' => '+55 61 99876 5432',
                'email' => '61998765432@octachat.com',
                'origem' => NULL,
                'url_octa' => '5c6636d6-a67d-483b-a5e1-30e300de34d7',
                'created_at' => '2024-01-01 16:05:00',
                'updated_at' => '2024-01-01 16:05:00',
                'primeira_mensagem_cliente' => 'Boa tarde, fazem entrega em Brasília?',
                'responsavel_contato' => 'Giovana',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170007,
                'nome' => 'Marcos Souza',
                'telefone' => '+55 71 98765 4321',
                'email' => '71987654321@octachat.com',
                'origem' => NULL,
                'url_octa' => 'a1a1de3c-57a9-4dfe-9ac4-34ee0eba22ba',
                'created_at' => '2024-01-01 17:30:00',
                'updated_at' => '2024-01-01 17:30:00',
                'primeira_mensagem_cliente' => 'Preciso de um orçamento para 10 bandeiras',
                'responsavel_contato' => 'Arte Arena Site',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => '2024-01-06 14:00:00',
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170008,
                'nome' => 'Carla Santos',
                'telefone' => '+55 81 99876 5432',
                'email' => '81998765432@octachat.com',
                'origem' => NULL,
                'url_octa' => '5d489451-c75e-47a9-814a-fed9034b1d10',
                'created_at' => '2024-01-01 18:15:00',
                'updated_at' => '2024-01-01 18:15:00',
                'primeira_mensagem_cliente' => 'Boa noite, qual o prazo de entrega?',
                'responsavel_contato' => 'Giovana',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Bandeira Personalizada',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170009,
                'nome' => 'Roberto Alves - 14535',
                'telefone' => '+55 91 98765 4321',
                'email' => '91987654321@octachat.com',
                'origem' => NULL,
                'url_octa' => '34858353-fa5a-4c40-addd-348f5df2ccdb',
                'created_at' => '2024-01-01 19:45:00',
                'updated_at' => '2024-01-01 19:45:00',
                'primeira_mensagem_cliente' => 'Quero fazer uma bandeira personalizada',
                'responsavel_contato' => 'Arte Arena Site',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ],
            [
                'id' => 24010170010,
                'nome' => 'Fernanda Costa',
                'telefone' => '+55 85 99876 5432',
                'email' => '85998765432@octachat.com',
                'origem' => NULL,
                'url_octa' => '6a42e86b-3c07-4ccf-9ec0-5776e8faf345',
                'created_at' => '2024-01-01 20:30:00',
                'updated_at' => '2024-01-01 20:30:00',
                'primeira_mensagem_cliente' => 'Olá, vocês fazem bandeiras para eventos?',
                'responsavel_contato' => 'Giovana',
                'tel_comercial_contato' => NULL,
                'tel_residencial_contato' => NULL,
                'status_do_contato' => '65037e67-b9b2-41ed-9fe1-d8719c15d63e',
                'numero_de_pedido_contato' => NULL,
                'nome_organizacao' => 'Octachat',
                'primeiro_telefone_organizacao' => NULL,
                'primeiro_dominio_organizacao' => 'octachat.com',
                'empresa' => 'Arte Arena',
                'data_agendamento' => NULL,
                'status_conversa' => NULL,
                'mensagem_template_id' => NULL,
                'contato_bloqueado' => 0,
                'contato_qualificado' => NULL,
                'motivo_perda' => NULL
            ]
        ];

        foreach (array_chunk($clientes, 100) as $chunk) {
            DB::table('crm_clientes')->insert($chunk);
        }
    }
} 