### Buscar um pedido de arte final específico
GET http://localhost:8000/api/producao/pedido-arte-final/1
Content-Type: application/json
Authorization: Bearer 24|zuBmga302KdqLIOEFT7VCuLeiY4CwteYVzyFtPaq1b4df5f9

