POST https://accounts.tiny.com.br/realms/tiny/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
client_id=tiny-api-89465a714c4275b8a7ffe83d057109241de0711a-1738606284
client_secret=2Ccqesiq04AzjWoCHIFpJL1wcdIb9VdE
redirect_uri=https://www.spacearena.net/auth/login
code=e17c56ad-f06d-47da-a2be-e8a151231eb5.d3883868-18f5-4e81-bef3-8e1e919f3001.d51c5b71-08a6-4a68-a3cc-fbb872b043eb


curl --location 'https://accounts.tiny.com.br/realms/tiny/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id=tiny-api-89465a714c4275b8a7ffe83d057109241de0711a-1738606284' \
--data-urlencode 'client_secret=2Ccqesiq04AzjWoCHIFpJL1wcdIb9VdE' \
--data-urlencode 'redirect_uri=https://www.spacearena.net/auth/login' \
--data-urlencode 'code=f2fdfa59-c35c-49be-b5e0-5302d6a7c842.d3883868-18f5-4e81-bef3-8e1e919f3001.d51c5b71-08a6-4a68-a3cc-fbb872b043eb' 
