
PUT http://localhost:8000/api/orcamento/backoffice/cliente-cadastro
Content-Type: application/json

{
    "tipo_pessoa": "PF",
    "nome_completo": "João da Silva5",
    "cpf": "123.456.789-05",
    "email": "joao@example.com",
    "celular": "99999-9999",
    "cep": "12345-678",
    "endereco": "Rua das Flores",
    "numero": "123",
    "complemento": "Apto 101",
    "bairro": "Centro",
    "cidade": "São Paulo",
    "uf": "SP",
    "cep_cobranca": "12345-678",
    "endereco_cobranca": "Rua das Rosas",
    "numero_cobranca": "456",
    "complemento_cobranca": "",
    "bairro_cobranca": "Jardins",
    "cidade_cobranca": "São Paulo",
    "uf_cobranca": "SP",
    "orcamento_id": "164"
}
