### Create a new account
POST http://localhost:8000/api/conta
Content-Type: application/json
Authorization: Bearer 1|LCZUkItmhKFLG8N47lKeMWptsn8BO8EjlFjSl84n267ea75f

{
    "titulo": "Pagamento da Internet",
    "descricao": "NET Claro",
    "valor": 300.50,
    "data_vencimento": "2025-12-31",
    "status": "pendente",
    "tipo": "a pagar",
    "user_id": 1
}

