@baseUrl = http://localhost:8000/api

### Register New User
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "Gabriel Felix Gomes",
    "email": "gabriel@artearena.com.br",
    "password": "artearena",
    "password_confirmation": "artearena"
}
