@baseUrl = http://localhost:8000/api

### Register New User
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "Leandro Damasio",
    "email": "ldamasio@gmail.com",
    "password": "artearena",
    "password_confirmation": "artearena"
}
