# @baseUrl = http://localhost:8000/api/login
@baseUrl = https://api-homolog.spacearena.net/api/login

@email = superadmin@artearena.com.br
@password = artearena

### Login
POST {{baseUrl}}
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

